// Code generated by protoc-gen-go. DO NOT EDIT.
// source: incident_report.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Incident struct {
	Id                   int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Date                 string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Time                 string                 `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Details              string                 `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	BasicDetails         *Incident_BasicDetails `protobuf:"bytes,5,opt,name=basicDetails,proto3" json:"basicDetails,omitempty"`
	MoreDetails          *Incident_MoreDetails  `protobuf:"bytes,6,opt,name=moreDetails,proto3" json:"moreDetails,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Incident) Reset()         { *m = Incident{} }
func (m *Incident) String() string { return proto.CompactTextString(m) }
func (*Incident) ProtoMessage()    {}
func (*Incident) Descriptor() ([]byte, []int) {
	return fileDescriptor_32ae80309190756b, []int{0}
}

func (m *Incident) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Incident.Unmarshal(m, b)
}
func (m *Incident) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Incident.Marshal(b, m, deterministic)
}
func (m *Incident) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Incident.Merge(m, src)
}
func (m *Incident) XXX_Size() int {
	return xxx_messageInfo_Incident.Size(m)
}
func (m *Incident) XXX_DiscardUnknown() {
	xxx_messageInfo_Incident.DiscardUnknown(m)
}

var xxx_messageInfo_Incident proto.InternalMessageInfo

func (m *Incident) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Incident) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Incident) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Incident) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *Incident) GetBasicDetails() *Incident_BasicDetails {
	if m != nil {
		return m.BasicDetails
	}
	return nil
}

func (m *Incident) GetMoreDetails() *Incident_MoreDetails {
	if m != nil {
		return m.MoreDetails
	}
	return nil
}

type Incident_BasicDetails struct {
	Environmental        bool                        `protobuf:"varint,1,opt,name=environmental,proto3" json:"environmental,omitempty"`
	IncidentType         string                      `protobuf:"bytes,2,opt,name=incidentType,proto3" json:"incidentType,omitempty"`
	Category             string                      `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	SubCategory          string                      `protobuf:"bytes,4,opt,name=subCategory,proto3" json:"subCategory,omitempty"`
	Site                 *Incident_BasicDetails_Site `protobuf:"bytes,5,opt,name=site,proto3" json:"site,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Incident_BasicDetails) Reset()         { *m = Incident_BasicDetails{} }
func (m *Incident_BasicDetails) String() string { return proto.CompactTextString(m) }
func (*Incident_BasicDetails) ProtoMessage()    {}
func (*Incident_BasicDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_32ae80309190756b, []int{0, 0}
}

func (m *Incident_BasicDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Incident_BasicDetails.Unmarshal(m, b)
}
func (m *Incident_BasicDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Incident_BasicDetails.Marshal(b, m, deterministic)
}
func (m *Incident_BasicDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Incident_BasicDetails.Merge(m, src)
}
func (m *Incident_BasicDetails) XXX_Size() int {
	return xxx_messageInfo_Incident_BasicDetails.Size(m)
}
func (m *Incident_BasicDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_Incident_BasicDetails.DiscardUnknown(m)
}

var xxx_messageInfo_Incident_BasicDetails proto.InternalMessageInfo

func (m *Incident_BasicDetails) GetEnvironmental() bool {
	if m != nil {
		return m.Environmental
	}
	return false
}

func (m *Incident_BasicDetails) GetIncidentType() string {
	if m != nil {
		return m.IncidentType
	}
	return ""
}

func (m *Incident_BasicDetails) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Incident_BasicDetails) GetSubCategory() string {
	if m != nil {
		return m.SubCategory
	}
	return ""
}

func (m *Incident_BasicDetails) GetSite() *Incident_BasicDetails_Site {
	if m != nil {
		return m.Site
	}
	return nil
}

type Incident_BasicDetails_Site struct {
	SiteName             string   `protobuf:"bytes,1,opt,name=siteName,proto3" json:"siteName,omitempty"`
	Contract             string   `protobuf:"bytes,2,opt,name=contract,proto3" json:"contract,omitempty"`
	SubCategory          string   `protobuf:"bytes,3,opt,name=subCategory,proto3" json:"subCategory,omitempty"`
	LocationDescription  string   `protobuf:"bytes,5,opt,name=locationDescription,proto3" json:"locationDescription,omitempty"`
	SafeToReturn         bool     `protobuf:"varint,6,opt,name=safeToReturn,proto3" json:"safeToReturn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Incident_BasicDetails_Site) Reset()         { *m = Incident_BasicDetails_Site{} }
func (m *Incident_BasicDetails_Site) String() string { return proto.CompactTextString(m) }
func (*Incident_BasicDetails_Site) ProtoMessage()    {}
func (*Incident_BasicDetails_Site) Descriptor() ([]byte, []int) {
	return fileDescriptor_32ae80309190756b, []int{0, 0, 0}
}

func (m *Incident_BasicDetails_Site) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Incident_BasicDetails_Site.Unmarshal(m, b)
}
func (m *Incident_BasicDetails_Site) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Incident_BasicDetails_Site.Marshal(b, m, deterministic)
}
func (m *Incident_BasicDetails_Site) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Incident_BasicDetails_Site.Merge(m, src)
}
func (m *Incident_BasicDetails_Site) XXX_Size() int {
	return xxx_messageInfo_Incident_BasicDetails_Site.Size(m)
}
func (m *Incident_BasicDetails_Site) XXX_DiscardUnknown() {
	xxx_messageInfo_Incident_BasicDetails_Site.DiscardUnknown(m)
}

var xxx_messageInfo_Incident_BasicDetails_Site proto.InternalMessageInfo

func (m *Incident_BasicDetails_Site) GetSiteName() string {
	if m != nil {
		return m.SiteName
	}
	return ""
}

func (m *Incident_BasicDetails_Site) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *Incident_BasicDetails_Site) GetSubCategory() string {
	if m != nil {
		return m.SubCategory
	}
	return ""
}

func (m *Incident_BasicDetails_Site) GetLocationDescription() string {
	if m != nil {
		return m.LocationDescription
	}
	return ""
}

func (m *Incident_BasicDetails_Site) GetSafeToReturn() bool {
	if m != nil {
		return m.SafeToReturn
	}
	return false
}

type Incident_MoreDetails struct {
	Investigator              string   `protobuf:"bytes,1,opt,name=investigator,proto3" json:"investigator,omitempty"`
	BlueLight                 bool     `protobuf:"varint,2,opt,name=blueLight,proto3" json:"blueLight,omitempty"`
	ReportedTo                string   `protobuf:"bytes,3,opt,name=reportedTo,proto3" json:"reportedTo,omitempty"`
	PotentialGreaterSeverity  bool     `protobuf:"varint,4,opt,name=potentialGreaterSeverity,proto3" json:"potentialGreaterSeverity,omitempty"`
	PersonInjured             bool     `protobuf:"varint,5,opt,name=personInjured,proto3" json:"personInjured,omitempty"`
	PersonTreatedByFirstAider bool     `protobuf:"varint,6,opt,name=personTreatedByFirstAider,proto3" json:"personTreatedByFirstAider,omitempty"`
	PersonFitToReturnToWork   bool     `protobuf:"varint,7,opt,name=personFitToReturnToWork,proto3" json:"personFitToReturnToWork,omitempty"`
	ImmediateAction           string   `protobuf:"bytes,8,opt,name=immediateAction,proto3" json:"immediateAction,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *Incident_MoreDetails) Reset()         { *m = Incident_MoreDetails{} }
func (m *Incident_MoreDetails) String() string { return proto.CompactTextString(m) }
func (*Incident_MoreDetails) ProtoMessage()    {}
func (*Incident_MoreDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_32ae80309190756b, []int{0, 1}
}

func (m *Incident_MoreDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Incident_MoreDetails.Unmarshal(m, b)
}
func (m *Incident_MoreDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Incident_MoreDetails.Marshal(b, m, deterministic)
}
func (m *Incident_MoreDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Incident_MoreDetails.Merge(m, src)
}
func (m *Incident_MoreDetails) XXX_Size() int {
	return xxx_messageInfo_Incident_MoreDetails.Size(m)
}
func (m *Incident_MoreDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_Incident_MoreDetails.DiscardUnknown(m)
}

var xxx_messageInfo_Incident_MoreDetails proto.InternalMessageInfo

func (m *Incident_MoreDetails) GetInvestigator() string {
	if m != nil {
		return m.Investigator
	}
	return ""
}

func (m *Incident_MoreDetails) GetBlueLight() bool {
	if m != nil {
		return m.BlueLight
	}
	return false
}

func (m *Incident_MoreDetails) GetReportedTo() string {
	if m != nil {
		return m.ReportedTo
	}
	return ""
}

func (m *Incident_MoreDetails) GetPotentialGreaterSeverity() bool {
	if m != nil {
		return m.PotentialGreaterSeverity
	}
	return false
}

func (m *Incident_MoreDetails) GetPersonInjured() bool {
	if m != nil {
		return m.PersonInjured
	}
	return false
}

func (m *Incident_MoreDetails) GetPersonTreatedByFirstAider() bool {
	if m != nil {
		return m.PersonTreatedByFirstAider
	}
	return false
}

func (m *Incident_MoreDetails) GetPersonFitToReturnToWork() bool {
	if m != nil {
		return m.PersonFitToReturnToWork
	}
	return false
}

func (m *Incident_MoreDetails) GetImmediateAction() string {
	if m != nil {
		return m.ImmediateAction
	}
	return ""
}

type Id struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id) Reset()         { *m = Id{} }
func (m *Id) String() string { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()    {}
func (*Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_32ae80309190756b, []int{1}
}

func (m *Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Id.Unmarshal(m, b)
}
func (m *Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Id.Marshal(b, m, deterministic)
}
func (m *Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id.Merge(m, src)
}
func (m *Id) XXX_Size() int {
	return xxx_messageInfo_Id.Size(m)
}
func (m *Id) XXX_DiscardUnknown() {
	xxx_messageInfo_Id.DiscardUnknown(m)
}

var xxx_messageInfo_Id proto.InternalMessageInfo

func (m *Id) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Incident)(nil), "grpc.Incident")
	proto.RegisterType((*Incident_BasicDetails)(nil), "grpc.Incident.BasicDetails")
	proto.RegisterType((*Incident_BasicDetails_Site)(nil), "grpc.Incident.BasicDetails.Site")
	proto.RegisterType((*Incident_MoreDetails)(nil), "grpc.Incident.MoreDetails")
	proto.RegisterType((*Id)(nil), "grpc.Id")
}

func init() { proto.RegisterFile("incident_report.proto", fileDescriptor_32ae80309190756b) }

var fileDescriptor_32ae80309190756b = []byte{
	// 543 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xdd, 0x8e, 0xd3, 0x3c,
	0x10, 0xfd, 0xfa, 0xb3, 0xdb, 0x74, 0xd2, 0xaf, 0x48, 0x06, 0x44, 0x08, 0x08, 0x55, 0x15, 0x17,
	0xe5, 0xa6, 0xa0, 0x85, 0x0b, 0x84, 0x56, 0x42, 0x5d, 0x56, 0xbb, 0xaa, 0x04, 0x5c, 0x78, 0x2b,
	0x71, 0x89, 0xdc, 0x78, 0x28, 0x86, 0xc4, 0x8e, 0x9c, 0x69, 0xa5, 0x3e, 0x00, 0xaf, 0xc4, 0xbb,
	0xf0, 0x1c, 0xbc, 0x00, 0x8a, 0x93, 0xb4, 0x49, 0x97, 0x72, 0xe7, 0x39, 0x33, 0x27, 0x9e, 0x73,
	0x66, 0x62, 0xb8, 0xaf, 0x74, 0xa4, 0x24, 0x6a, 0xfa, 0x6c, 0x31, 0x35, 0x96, 0xa6, 0xa9, 0x35,
	0x64, 0x58, 0x77, 0x65, 0xd3, 0x68, 0xfc, 0xab, 0x07, 0xde, 0xbc, 0xcc, 0xb3, 0x21, 0xb4, 0x95,
	0x0c, 0x5a, 0xa3, 0xd6, 0xe4, 0x84, 0xb7, 0x95, 0x64, 0x0c, 0xba, 0x52, 0x10, 0x06, 0xed, 0x51,
	0x6b, 0xd2, 0xe7, 0xee, 0x9c, 0x63, 0xa4, 0x12, 0x0c, 0x3a, 0x05, 0x96, 0x9f, 0x59, 0x00, 0x3d,
	0x89, 0x24, 0x54, 0x9c, 0x05, 0x5d, 0x07, 0x57, 0x21, 0x7b, 0x0b, 0x83, 0xa5, 0xc8, 0x54, 0x74,
	0x59, 0xa6, 0x4f, 0x46, 0xad, 0x89, 0x7f, 0xf6, 0x68, 0x9a, 0xdf, 0x3d, 0xad, 0xee, 0x9d, 0x5e,
	0xd4, 0x4a, 0x78, 0x83, 0xc0, 0xce, 0xc1, 0x4f, 0x8c, 0xc5, 0x8a, 0x7f, 0xea, 0xf8, 0xe1, 0x01,
	0xff, 0xc3, 0xbe, 0x82, 0xd7, 0xcb, 0xc3, 0x1f, 0x1d, 0x18, 0xd4, 0x3f, 0xce, 0x9e, 0xc2, 0xff,
	0xa8, 0x37, 0xca, 0x1a, 0x9d, 0xa0, 0x26, 0x11, 0x3b, 0xb1, 0x1e, 0x6f, 0x82, 0x6c, 0x0c, 0x83,
	0xca, 0xb3, 0xc5, 0x36, 0xad, 0xf4, 0x37, 0x30, 0x16, 0x82, 0x17, 0x09, 0xc2, 0x95, 0xb1, 0xdb,
	0xd2, 0x8b, 0x5d, 0xcc, 0x46, 0xe0, 0x67, 0xeb, 0xe5, 0xbb, 0x2a, 0x5d, 0x78, 0x52, 0x87, 0xd8,
	0x2b, 0xe8, 0x66, 0x8a, 0xb0, 0xf4, 0x63, 0xf4, 0x0f, 0x3f, 0xa6, 0x37, 0x8a, 0x90, 0xbb, 0xea,
	0xf0, 0x67, 0x0b, 0xba, 0x79, 0x98, 0x5f, 0x9e, 0x03, 0x1f, 0x45, 0x82, 0x4e, 0x41, 0x9f, 0xef,
	0x62, 0xd7, 0x98, 0xd1, 0x64, 0x45, 0x44, 0x65, 0xe3, 0xbb, 0xf8, 0xb0, 0xb1, 0xce, 0xed, 0xc6,
	0x5e, 0xc0, 0xdd, 0xd8, 0x44, 0x82, 0x94, 0xd1, 0x97, 0x98, 0x45, 0x56, 0xa5, 0xf9, 0xd1, 0xf5,
	0xd9, 0xe7, 0x7f, 0x4b, 0xe5, 0x66, 0x65, 0xe2, 0x0b, 0x2e, 0x0c, 0x47, 0x5a, 0x5b, 0xed, 0x46,
	0xe4, 0xf1, 0x06, 0x16, 0xfe, 0x6e, 0x83, 0x5f, 0x1b, 0x52, 0x61, 0xf0, 0x06, 0x33, 0x52, 0x2b,
	0x41, 0xc6, 0x96, 0x1a, 0x1a, 0x18, 0x7b, 0x0c, 0xfd, 0x65, 0xbc, 0xc6, 0xf7, 0x6a, 0xf5, 0xb5,
	0x10, 0xe2, 0xf1, 0x3d, 0xc0, 0x9e, 0x00, 0x14, 0xdb, 0x8c, 0x72, 0x61, 0x4a, 0x21, 0x35, 0x84,
	0xbd, 0x81, 0x20, 0x35, 0x84, 0x9a, 0x94, 0x88, 0xaf, 0x2d, 0x0a, 0x42, 0x7b, 0x83, 0x1b, 0xb4,
	0x8a, 0x8a, 0x79, 0x78, 0xfc, 0x68, 0x3e, 0x5f, 0x92, 0x14, 0x6d, 0x66, 0xf4, 0x5c, 0x7f, 0x5b,
	0x5b, 0x94, 0x4e, 0xbd, 0xc7, 0x9b, 0x20, 0x3b, 0x87, 0x87, 0x05, 0xb0, 0x70, 0x74, 0x79, 0xb1,
	0xbd, 0x52, 0x36, 0xa3, 0x99, 0x92, 0x68, 0x4b, 0x13, 0x8e, 0x17, 0xb0, 0xd7, 0xf0, 0xa0, 0x48,
	0x5e, 0x29, 0xaa, 0x6c, 0x5a, 0x98, 0x4f, 0xc6, 0x7e, 0x0f, 0x7a, 0x8e, 0x7b, 0x2c, 0xcd, 0x26,
	0x70, 0x47, 0x25, 0x09, 0x4a, 0x25, 0x08, 0x67, 0x91, 0x9b, 0x8e, 0xe7, 0xe4, 0x1f, 0xc2, 0xe3,
	0x7b, 0xd0, 0x9e, 0xcb, 0xc3, 0x9f, 0xfa, 0x2c, 0x86, 0x61, 0xb5, 0x68, 0xdc, 0xf9, 0xc5, 0x9e,
	0x81, 0x7f, 0x8d, 0xb4, 0x7b, 0x05, 0xbc, 0x72, 0x1b, 0x65, 0x38, 0x6c, 0xee, 0xe5, 0xf8, 0x3f,
	0xf6, 0x1c, 0xfc, 0x99, 0x94, 0xfb, 0x07, 0xa3, 0x59, 0x70, 0x9b, 0xb0, 0x3c, 0x75, 0x8f, 0xcd,
	0xcb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x46, 0x16, 0x05, 0x8a, 0x85, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IncidentReportClient is the client API for IncidentReport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IncidentReportClient interface {
	GetIncident(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Incident, error)
	AddIncident(ctx context.Context, in *Incident, opts ...grpc.CallOption) (*Incident, error)
}

type incidentReportClient struct {
	cc *grpc.ClientConn
}

func NewIncidentReportClient(cc *grpc.ClientConn) IncidentReportClient {
	return &incidentReportClient{cc}
}

func (c *incidentReportClient) GetIncident(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Incident, error) {
	out := new(Incident)
	err := c.cc.Invoke(ctx, "/grpc.IncidentReport/GetIncident", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *incidentReportClient) AddIncident(ctx context.Context, in *Incident, opts ...grpc.CallOption) (*Incident, error) {
	out := new(Incident)
	err := c.cc.Invoke(ctx, "/grpc.IncidentReport/AddIncident", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IncidentReportServer is the server API for IncidentReport service.
type IncidentReportServer interface {
	GetIncident(context.Context, *Id) (*Incident, error)
	AddIncident(context.Context, *Incident) (*Incident, error)
}

func RegisterIncidentReportServer(s *grpc.Server, srv IncidentReportServer) {
	s.RegisterService(&_IncidentReport_serviceDesc, srv)
}

func _IncidentReport_GetIncident_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncidentReportServer).GetIncident(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.IncidentReport/GetIncident",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncidentReportServer).GetIncident(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _IncidentReport_AddIncident_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Incident)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncidentReportServer).AddIncident(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.IncidentReport/AddIncident",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncidentReportServer).AddIncident(ctx, req.(*Incident))
	}
	return interceptor(ctx, in, info, handler)
}

var _IncidentReport_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.IncidentReport",
	HandlerType: (*IncidentReportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIncident",
			Handler:    _IncidentReport_GetIncident_Handler,
		},
		{
			MethodName: "AddIncident",
			Handler:    _IncidentReport_AddIncident_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "incident_report.proto",
}
