// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type BasicDetails struct {
	Environmental bool   `json:"environmental"`
	IncidentType  string `json:"incidentType"`
	Category      string `json:"category"`
	SubCategory   string `json:"subCategory"`
	Site          Site   `json:"site"`
}

type Incident struct {
	ID           string       `json:"id"`
	Date         string       `json:"date"`
	Time         string       `json:"time"`
	Details      string       `json:"details"`
	BasicDetails BasicDetails `json:"basicDetails"`
	MoreDetails  MoreDetails  `json:"moreDetails"`
}

type MoreDetails struct {
	Investigator              string `json:"investigator"`
	BlueLight                 bool   `json:"blueLight"`
	ReportedTo                string `json:"reportedTo"`
	PotentialGreaterSeverity  bool   `json:"potentialGreaterSeverity"`
	PersonInjured             bool   `json:"personInjured"`
	PersonTreatedByFirstAider bool   `json:"personTreatedByFirstAider"`
	PersonFitToReturnToWork   bool   `json:"personFitToReturnToWork"`
	ImmediateAction           string `json:"immediateAction"`
}

type Site struct {
	SiteName            string `json:"siteName"`
	Contract            string `json:"contract"`
	SubCategory         string `json:"subCategory"`
	LocationDescription string `json:"locationDescription"`
	SafeToReturn        bool   `json:"safeToReturn"`
}

type NewBasicDetails struct {
	Environmental bool    `json:"environmental"`
	IncidentType  string  `json:"incidentType"`
	Category      string  `json:"category"`
	SubCategory   string  `json:"subCategory"`
	Site          NewSite `json:"site"`
}

type NewIncident struct {
	ID           string          `json:"id"`
	Date         string          `json:"date"`
	Time         string          `json:"time"`
	Details      string          `json:"details"`
	BasicDetails NewBasicDetails `json:"basicDetails"`
	MoreDetails  NewMoreDetails  `json:"moreDetails"`
}

type NewMoreDetails struct {
	Investigator              string `json:"investigator"`
	BlueLight                 bool   `json:"blueLight"`
	ReportedTo                string `json:"reportedTo"`
	PotentialGreaterSeverity  bool   `json:"potentialGreaterSeverity"`
	PersonInjured             bool   `json:"personInjured"`
	PersonTreatedByFirstAider bool   `json:"personTreatedByFirstAider"`
	PersonFitToReturnToWork   bool   `json:"personFitToReturnToWork"`
	ImmediateAction           string `json:"immediateAction"`
}

type NewSite struct {
	SiteName            string `json:"siteName"`
	Contract            string `json:"contract"`
	SubCategory         string `json:"subCategory"`
	LocationDescription string `json:"locationDescription"`
	SafeToReturn        bool   `json:"safeToReturn"`
}
